-- H2 2.2.224;
;
CREATE USER IF NOT EXISTS "SA" SALT 'c4c5aa25e1f3d0b3' HASH '1692455844a3a235e26436ec427087d7c41c1712ddcffbf61d3124912a932b3b' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."CATEGORY"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 9) NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "PARENT_ID" BIGINT
);
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.CATEGORY;
INSERT INTO "PUBLIC"."CATEGORY" VALUES
                                    (1, 'Baby, Home & Shoes', NULL),
                                    (2, 'Games', NULL),
                                    (3, 'Automotive', NULL),
                                    (4, 'Games, Garden & Toys', 3),
                                    (5, 'Games, Home & Shoes', 3),
                                    (6, 'Garden, Health & Shoes', 1),
                                    (7, 'Beauty & Music', 1),
                                    (8, 'Baby, Music & Shoes', 1);
CREATE MEMORY TABLE "PUBLIC"."CUSTOMER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 11) NOT NULL,
    "NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER;               
INSERT INTO "PUBLIC"."CUSTOMER" VALUES
                                    (1, 'Miss Sammie Wintheiser'),
                                    (2, 'Ellsworth Rohan'),
                                    (3, 'Lonny Kertzmann III'),
                                    (4, 'Ariel Watsica'),
                                    (5, 'Becky Zulauf'),
                                    (6, 'Mrs. Caroyln Wisozk'),
                                    (7, 'Vergie Adams PhD'),
                                    (8, 'Elroy Stracke'),
                                    (9, 'Murray McCullough'),
                                    (10, 'Darwin Schmeler');
CREATE MEMORY TABLE "PUBLIC"."CUSTOMER_ORDER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 20) NOT NULL,
    "CUSTOMER_ID" BIGINT
);
ALTER TABLE "PUBLIC"."CUSTOMER_ORDER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3B" PRIMARY KEY("ID");
-- 19 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER_ORDER;         
INSERT INTO "PUBLIC"."CUSTOMER_ORDER" VALUES
                                          (1, 1),
                                          (2, 2),
                                          (3, 2),
                                          (4, 3),
                                          (5, 3),
                                          (6, 4),
                                          (7, 4),
                                          (8, 5),
                                          (9, 5),
                                          (10, 6),
                                          (11, 6),
                                          (12, 7),
                                          (13, 7),
                                          (14, 8),
                                          (15, 8),
                                          (16, 9),
                                          (17, 9),
                                          (18, 10),
                                          (19, 10);
CREATE MEMORY TABLE "PUBLIC"."MERCHANT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) NOT NULL,
    "ADDRESS" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."MERCHANT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.MERCHANT;
INSERT INTO "PUBLIC"."MERCHANT" VALUES
                                    (1, '14362 Abbott Canyon', 'McDermott LLC'),
                                    (2, '5230 Pagac Square', 'Dooley-Marquardt'),
                                    (3, '89056 Mireya Mountain', 'Aufderhar-Bergstrom'),
                                    (4, '43033 Jacobson Hollow', 'Stroman Group'),
                                    (5, '83635 Regena Coves', 'Russel-Cormier');
CREATE MEMORY TABLE "PUBLIC"."OPTION_TYPE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."OPTION_TYPE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.OPTION_TYPE;             
INSERT INTO "PUBLIC"."OPTION_TYPE" VALUES
                                       (1, 'Color'),
                                       (2, 'Size');
CREATE MEMORY TABLE "PUBLIC"."OPTION_VALUE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 9) NOT NULL,
    "OPTION_VALUE" CHARACTER VARYING(255),
    "OPTION_TYPE_ID" BIGINT
);
ALTER TABLE "PUBLIC"."OPTION_VALUE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.OPTION_VALUE;            
INSERT INTO "PUBLIC"."OPTION_VALUE" VALUES
                                        (1, 'Red', 1),
                                        (2, 'Blue', 1),
                                        (3, 'Green', 1),
                                        (4, 'Yellow', 1),
                                        (5, 'S', 2),
                                        (6, 'M', 2),
                                        (7, 'L', 2),
                                        (8, 'XL', 2);
CREATE MEMORY TABLE "PUBLIC"."ORDER_ITEM_OPTION_VALUE"(
    "ORDER_ITEM_ID" BIGINT NOT NULL,
    "OPTION_VALUE_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."ORDER_ITEM_OPTION_VALUE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6F" PRIMARY KEY("ORDER_ITEM_ID", "OPTION_VALUE_ID");
-- 108 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_ITEM_OPTION_VALUE;               
INSERT INTO "PUBLIC"."ORDER_ITEM_OPTION_VALUE" VALUES
                                                   (1, 4),
                                                   (1, 7),
                                                   (2, 4),
                                                   (2, 8),
                                                   (3, 4),
                                                   (3, 7),
                                                   (4, 4),
                                                   (4, 8),
                                                   (5, 1),
                                                   (5, 8),
                                                   (6, 4),
                                                   (6, 8),
                                                   (7, 6),
                                                   (7, 3),
                                                   (8, 1),
                                                   (9, 4),
                                                   (9, 7),
                                                   (10, 4),
                                                   (11, 4),
                                                   (11, 8),
                                                   (12, 4),
                                                   (12, 6),
                                                   (13, 4),
                                                   (14, 4),
                                                   (14, 8),
                                                   (15, 4),
                                                   (15, 6),
                                                   (16, 1),
                                                   (16, 6),
                                                   (17, 1),
                                                   (17, 8),
                                                   (18, 1),
                                                   (19, 2),
                                                   (19, 6),
                                                   (20, 4),
                                                   (20, 6),
                                                   (21, 4),
                                                   (22, 2),
                                                   (22, 6),
                                                   (23, 4),
                                                   (23, 8),
                                                   (24, 1),
                                                   (24, 8),
                                                   (25, 4),
                                                   (25, 7),
                                                   (26, 4),
                                                   (26, 8),
                                                   (27, 5),
                                                   (28, 4),
                                                   (28, 7),
                                                   (29, 4),
                                                   (29, 8),
                                                   (30, 8),
                                                   (31, 4),
                                                   (31, 8),
                                                   (32, 8),
                                                   (33, 2),
                                                   (33, 6),
                                                   (34, 1),
                                                   (34, 8),
                                                   (35, 4),
                                                   (36, 3),
                                                   (37, 2),
                                                   (38, 2),
                                                   (38, 6),
                                                   (39, 1),
                                                   (39, 5),
                                                   (40, 4),
                                                   (40, 8),
                                                   (41, 8),
                                                   (42, 6),
                                                   (42, 3),
                                                   (43, 4),
                                                   (43, 7),
                                                   (44, 1),
                                                   (45, 1),
                                                   (45, 8),
                                                   (46, 6),
                                                   (46, 3),
                                                   (47, 5),
                                                   (48, 1),
                                                   (48, 8),
                                                   (49, 4),
                                                   (49, 7),
                                                   (50, 2),
                                                   (50, 6),
                                                   (51, 4),
                                                   (51, 6),
                                                   (52, 4),
                                                   (52, 8),
                                                   (53, 3),
                                                   (54, 4),
                                                   (54, 6),
                                                   (55, 1),
                                                   (55, 8),
                                                   (56, 4),
                                                   (56, 8),
                                                   (57, 4),
                                                   (57, 8),
                                                   (58, 4),
                                                   (58, 6),
                                                   (59, 4),
                                                   (59, 8),
                                                   (60, 3),
                                                   (61, 1),
                                                   (61, 5),
                                                   (62, 2),
                                                   (62, 6);
CREATE MEMORY TABLE "PUBLIC"."ORDER_ITEM"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 63) NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "ORDER_ID" BIGINT,
    "PRODUCT_ID" BIGINT
);
ALTER TABLE "PUBLIC"."ORDER_ITEM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");
-- 62 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_ITEM;             
INSERT INTO "PUBLIC"."ORDER_ITEM" VALUES
                                      (1, 3, 1, 6),
                                      (2, 4, 1, 13),
                                      (3, 4, 1, 20),
                                      (4, 2, 2, 16),
                                      (5, 3, 2, 8),
                                      (6, 4, 2, 10),
                                      (7, 3, 3, 15),
                                      (8, 3, 3, 3),
                                      (9, 4, 3, 20),
                                      (10, 4, 3, 18),
                                      (11, 1, 4, 2),
                                      (12, 3, 4, 7),
                                      (13, 4, 4, 12),
                                      (14, 4, 4, 16),
                                      (15, 2, 5, 7),
                                      (16, 3, 5, 9),
                                      (17, 3, 5, 8),
                                      (18, 4, 5, 11),
                                      (19, 2, 6, 4),
                                      (20, 2, 6, 7),
                                      (21, 1, 7, 18),
                                      (22, 1, 7, 4),
                                      (23, 1, 7, 10),
                                      (24, 3, 7, 19),
                                      (25, 2, 8, 20),
                                      (26, 2, 8, 2),
                                      (27, 2, 8, 5),
                                      (28, 4, 8, 20),
                                      (29, 1, 9, 2),
                                      (30, 2, 9, 5),
                                      (31, 4, 9, 16),
                                      (32, 4, 9, 5),
                                      (33, 1, 10, 4),
                                      (34, 3, 10, 19),
                                      (35, 4, 10, 18),
                                      (36, 1, 11, 12),
                                      (37, 4, 11, 18),
                                      (38, 4, 11, 4),
                                      (39, 4, 11, 14),
                                      (40, 3, 12, 2),
                                      (41, 4, 12, 5),
                                      (42, 4, 12, 15),
                                      (43, 4, 13, 20),
                                      (44, 4, 13, 11),
                                      (45, 4, 13, 19),
                                      (46, 1, 14, 15),
                                      (47, 4, 14, 5),
                                      (48, 1, 15, 19),
                                      (49, 1, 15, 6),
                                      (50, 4, 15, 4),
                                      (51, 4, 15, 7),
                                      (52, 4, 16, 13),
                                      (53, 4, 16, 3),
                                      (54, 4, 17, 7),
                                      (55, 4, 17, 8),
                                      (56, 4, 17, 2),
                                      (57, 1, 18, 1),
                                      (58, 3, 18, 7),
                                      (59, 4, 18, 16),
                                      (60, 4, 18, 3),
                                      (61, 1, 19, 14),
                                      (62, 3, 19, 17);
CREATE MEMORY TABLE "PUBLIC"."PRODUCT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 21) NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "PRICE" FLOAT(53) NOT NULL,
    "SKU" CHARACTER VARYING(255),
    "STOCK" INTEGER NOT NULL,
    "MERCHANT_ID" BIGINT
);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_18" PRIMARY KEY("ID");
-- 20 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT;
INSERT INTO "PUBLIC"."PRODUCT" VALUES
                                   (1, 'Practical Concrete Keyboard', 76.11, 'StellarDiscount455305', 62, 3),
                                   (2, 'Awesome Aluminum Keyboard', 56.34, 'PremiumSavings568351', 29, 4),
                                   (3, 'Intelligent Marble Gloves', 69.12, 'IncredibleDeal901273', 70, 1),
                                   (4, 'Enormous Wooden Computer', 15.57, 'IncrediblePromo887234', 6, 4),
                                   (5, 'Ergonomic Plastic Shirt', 87.15, 'PremiumDeal852872', 79, 5),
                                   (6, 'Enormous Rubber Pants', 8.34, 'SpecialCode295675', 56, 1),
                                   (7, 'Aerodynamic Steel Bottle', 47.15, 'SpecialPromo675109', 17, 1),
                                   (8, 'Rustic Bronze Shirt', 20.23, 'SweetDiscount874242', 33, 5),
                                   (9, 'Incredible Concrete Pants', 37.35, 'GoodDeal309904', 28, 4),
                                   (10, 'Mediocre Wooden Watch', 93.21, 'GreatCode200451', 4, 3),
                                   (11, 'Heavy Duty Wooden Clock', 9.06, 'AwesomeCode003689', 64, 1),
                                   (12, 'Intelligent Granite Plate', 70.41, 'CoolDeal685414', 73, 2),
                                   (13, 'Awesome Aluminum Pants', 57.46, 'AwesomeCode843751', 68, 5),
                                   (14, 'Fantastic Granite Chair', 27.86, 'PremiumDeal407568', 5, 5),
                                   (15, 'Enormous Cotton Watch', 26.19, 'GoodPromo380523', 4, 1),
                                   (16, 'Durable Steel Plate', 24.4, 'StellarSavings808670', 37, 2),
                                   (17, 'Ergonomic Paper Shirt', 98.52, 'PremiumDiscount557346', 38, 4),
                                   (18, 'Intelligent Concrete Bottle', 87.54, 'GreatDeal023125', 12, 1),
                                   (19, 'Rustic Linen Table', 14.92, 'GoodPromo038432', 49, 3),
                                   (20, 'Practical Paper Bench', 45.66, 'KillerPrice347080', 28, 5);
CREATE MEMORY TABLE "PUBLIC"."PRODUCT_CATEGORY"(
    "PRODUCT_ID" BIGINT NOT NULL,
    "CATEGORY_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."PRODUCT_CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_39" PRIMARY KEY("PRODUCT_ID", "CATEGORY_ID");
-- 40 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_CATEGORY;       
INSERT INTO "PUBLIC"."PRODUCT_CATEGORY" VALUES
                                            (1, 6),
                                            (1, 7),
                                            (2, 4),
                                            (2, 7),
                                            (3, 4),
                                            (3, 6),
                                            (4, 5),
                                            (4, 8),
                                            (5, 4),
                                            (5, 5),
                                            (6, 6),
                                            (6, 8),
                                            (7, 7),
                                            (7, 8),
                                            (8, 4),
                                            (8, 6),
                                            (9, 6),
                                            (9, 7),
                                            (10, 4),
                                            (10, 7),
                                            (11, 4),
                                            (11, 8),
                                            (12, 5),
                                            (12, 7),
                                            (13, 4),
                                            (13, 8),
                                            (14, 4),
                                            (14, 8),
                                            (15, 6),
                                            (15, 8),
                                            (16, 6),
                                            (16, 8),
                                            (17, 6),
                                            (17, 7),
                                            (18, 4),
                                            (18, 6),
                                            (19, 4),
                                            (19, 8),
                                            (20, 4),
                                            (20, 8);
CREATE MEMORY TABLE "PUBLIC"."PRODUCT_OPTION_VALUE"(
    "PRODUCT_ID" BIGINT NOT NULL,
    "OPTION_VALUE_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."PRODUCT_OPTION_VALUE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("PRODUCT_ID", "OPTION_VALUE_ID");
-- 40 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_OPTION_VALUE;   
INSERT INTO "PUBLIC"."PRODUCT_OPTION_VALUE" VALUES
                                                (1, 4),
                                                (1, 8),
                                                (2, 4),
                                                (2, 8),
                                                (3, 1),
                                                (3, 3),
                                                (4, 2),
                                                (4, 6),
                                                (5, 8),
                                                (5, 5),
                                                (6, 4),
                                                (6, 7),
                                                (7, 4),
                                                (7, 6),
                                                (8, 1),
                                                (8, 8),
                                                (9, 1),
                                                (9, 6),
                                                (10, 4),
                                                (10, 8),
                                                (11, 4),
                                                (11, 1),
                                                (12, 4),
                                                (12, 3),
                                                (13, 4),
                                                (13, 8),
                                                (14, 1),
                                                (14, 5),
                                                (15, 6),
                                                (15, 3),
                                                (16, 4),
                                                (16, 8),
                                                (17, 2),
                                                (17, 6),
                                                (18, 4),
                                                (18, 2),
                                                (19, 1),
                                                (19, 8),
                                                (20, 4),
                                                (20, 7);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."FKK47QMALV2PG906HEIELTEUBU7" FOREIGN KEY("MERCHANT_ID") REFERENCES "PUBLIC"."MERCHANT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCT_OPTION_VALUE" ADD CONSTRAINT "PUBLIC"."FKGD1GWXR2W8E215NS9POIDOQE7" FOREIGN KEY("OPTION_VALUE_ID") REFERENCES "PUBLIC"."OPTION_VALUE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ORDER_ITEM" ADD CONSTRAINT "PUBLIC"."FKGV4BNMO7CBIB2NH0B2RW9YVIR" FOREIGN KEY("ORDER_ID") REFERENCES "PUBLIC"."CUSTOMER_ORDER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ORDER_ITEM" ADD CONSTRAINT "PUBLIC"."FK551LOSX9J75SS5D6BFSQVIJNA" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ORDER_ITEM_OPTION_VALUE" ADD CONSTRAINT "PUBLIC"."FK1AWDN9AW97CQLJQVN5PKS3IDT" FOREIGN KEY("ORDER_ITEM_ID") REFERENCES "PUBLIC"."ORDER_ITEM"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."FK2Y94SVPMQTTX80MSHYNY85WQR" FOREIGN KEY("PARENT_ID") REFERENCES "PUBLIC"."CATEGORY"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."OPTION_VALUE" ADD CONSTRAINT "PUBLIC"."FKNVWK04QEGAUQB5DFTV80IMUXX" FOREIGN KEY("OPTION_TYPE_ID") REFERENCES "PUBLIC"."OPTION_TYPE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCT_OPTION_VALUE" ADD CONSTRAINT "PUBLIC"."FK2ORSP8E9OENAVXNQ98NBXRM1S" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCT_CATEGORY" ADD CONSTRAINT "PUBLIC"."FKKUD35LS1D40WPJB5HTPP14Q4E" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."CATEGORY"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ORDER_ITEM_OPTION_VALUE" ADD CONSTRAINT "PUBLIC"."FKS37UO1R1SO4FSMRCSCUSVLX04" FOREIGN KEY("OPTION_VALUE_ID") REFERENCES "PUBLIC"."OPTION_VALUE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCT_CATEGORY" ADD CONSTRAINT "PUBLIC"."FK2K3SMHBRUEDLCRVU6CLUED06X" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."CUSTOMER_ORDER" ADD CONSTRAINT "PUBLIC"."FKF9ABD30BHIQVUGAYXLPQ8RYQ9" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."CUSTOMER"("ID") NOCHECK;          
