spring:
  application:
    name: auth-micro
  security:
    user:
      name: ${SERVICE_USERNAME:admin}
      password: ${SERVICE_PASS:pass}
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_USERNAME:admin}:${SERVICE_PASS:pass}@localhost:8089/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.web: trace
    org.springframework.web.servlet.DispatcherServlet: TRACE

jwt-variables:
  secret-key: 674c6b706f2fdc13c2b98a6b7f32be947ba4c2a5acf23776295cc1a077a3674e
  expiration-time: 3600000 #3600000