spring:
  application:
    name: auth-micro
  security:
    user:
      name: ${SERVICE_USERNAME:admin}
      password: ${SERVICE_PASS:pass}
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 0
  servlet:
    context-path: /auth-service

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_USERNAME:admin}:${SERVICE_PASS:pass}@localhost:8089/eureka

# Logging
logging:
  level:
    org.springframework.web: trace
    org.springframework.web.servlet.DispatcherServlet: TRACE

jwt-variables:
  EXPIRES_ACCESS_TOKEN_MINUTE: 90
  ISSUER: dev
  KEY: asdqwe123+K3Y