spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-micro-route
          uri: lb://auth-micro
          predicates:
            - Path=/auth-micro/**
          filters:
            - StripPrefix=1

        - id: project-micro-route
          uri: lb://project-micro
          predicates:
            - Path=/project-micro/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: task-micro-route
          uri: lb://task-micro
          predicates:
            - Path=/task-micro/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: analytics-micro-route
          uri: lb://analytics-micro
          predicates:
            - Path=/analytics-micro/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_USERNAME:admin}:${SERVICE_PASS:pass}@localhost:8089/eureka
  instance:
    prefer-ip-address: true

# Logging
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE

